"""Neural Archaeology — computational core.

This package is the scientific substrate of the platform. It has **no
framework dependencies** (no FastAPI, no web). Everything here is pure,
deterministic NumPy computation, so it can be tested, embedded, or reused
outside the API layer.

Public API
----------
- ``run_experiment``            — the single entry point (section 12)
- ``Experiment`` / ``ExperimentConfig`` / ``TaskConfig`` — data objects
- ``MECHANISM_REGISTRY``        — pluggable state-update mechanisms (section 6)
- ``generate_task``             — synthetic controlled-memory task generator (section 8)
- ``compute_metrics``           — metric definitions + computation (section 11)

Determinism guarantee
---------------------
Every random number used anywhere in the core flows from a
``numpy.random.Generator`` seeded by the experiment seed (or an explicitly
derived per-event seed). Running ``run_experiment`` twice with the same
config produces byte-identical results.
"""

from .analysis import (
    ablate_event,
    analyze_memory_contribution,
    compare_experiments,
    compare_states,
    experiment_timeline,
    inspect_state,
)
from .events import Event
from .experiment import (
    SCHEMA_VERSION,
    Experiment,
    ExperimentConfig,
    load_experiment,
    save_experiment,
)
from .mechanisms import (
    MECHANISM_INFO,
    MECHANISM_REGISTRY,
    MechanismParams,
    create_mechanism,
)
from .memory import (
    Memory,
    RecallResult,
    SIMILARITY_MEASURES,
    TextMemory,
    UpdateResult,
    encode_memory,
    interference_model,
    recall_memory,
    similarity,
    write_memory,
    write_memories,
)
from .metrics import METRIC_DEFINITIONS, compute_metrics
from .lab import (
    CompetingHypothesesGroup,
    ExperimentGraph,
    ExperimentQueue,
    ExperimentValidator,
    Hypothesis,
    HypothesisStatus,
    LabExperiment,
    PredictedDirection,
    Prediction,
    Variable,
    VARIABLE_REGISTRY,
    analyze_sweep_relationship,
    detect_nonlinear_patterns,
    diff_lab_experiments,
    export_experiment_csv,
    export_experiment_json,
    find_discriminating_experiment,
    generate_scientific_report,
    reproduce_lab_experiment,
    run_condition_trials,
    run_controlled_comparison,
    run_grid_sweep,
    run_parameter_sweep,
    suggest_next_experiment,
)
from .counterfactual import (
    BranchType,
    CounterfactualExperiment,
    CounterfactualStatus,
    CounterfactualTree,
    CounterfactualValidationError,
    DivergenceClassification,
    DivergenceProfile,
    DivergenceStep,
    Intervention,
    InterventionType,
    ReplayStrategy,
    Timeline,
    TimelineNode,
    classify_divergence,
    compare_multiple_histories,
    compute_divergence_profile,
    create_ablation,
    create_change_similarity_intervention,
    create_change_strength_intervention,
    create_duplicate_intervention,
    create_freeze_memory_intervention,
    create_inject_memory_intervention,
    create_modify_intervention,
    create_move_intervention,
    create_remove_intervention,
    create_replace_intervention,
    create_reset_memory_intervention,
    create_surgery,
    create_temporal_surgery_intervention,
    diff_histories,
    estimate_event_contribution,
    export_counterfactual_json,
    export_divergence_csv,
    find_minimal_intervention,
    generate_counterfactual_explanation,
    prepare_counterfactual_task,
    replay_counterfactual_engine,
    reproduce_counterfactual,
    run_counterfactual,
    search_counterfactuals,
    validate_intervention,
)
from .runner import run_experiment
from .scenarios import (
    SCENARIOS,
    capacity_sweep,
    collision_report,
    interference_matrix,
    order_comparison,
    retention_curve,
    run_scenario,
    strength_sweep,
)
from .collision import (
    CollisionConfig,
    CollisionMemory,
    CollisionResult,
    SynapticPathwayClassification,
    perform_collision_counterfactual,
    perform_collision_surgery,
    run_collision_experiment,
    run_order_comparison,
    run_three_condition_suite,
)
from .forensics import (
    CORE_LEARNING_OBJECTIVES,
    VERIFIED_SOURCES,
    CandidateHypothesis,
    CaseGenerator,
    CustomExperimentConfig,
    CustomExperimentResult,
    DetectiveScore,
    EvidenceItem,
    InvestigationCase,
    ResearchLabEngine,
    ScientificSource,
    score_investigation,
)
from .observatory import (
    AdaptiveObservatoryEngine,
    ChangeDetection,
    EnvironmentShiftReport,
    LearnerPrediction,
    ObservatoryProbe,
    ObservatorySession,
    ObservatorySnapshot,
    StabilityPlasticityMetrics,
    StreamEvent,
    SynapticWeatherPoint,
)
from .fingerprint import (
    FingerprintChallenge,
    FingerprintComparison,
    FingerprintEvolution,
    MemoryBranchNode,
    MemoryDistanceMap,
    MemoryDistancePoint,
    MemoryGenomeEngine,
    OutlierReport,
    SynapticFingerprint,
)
from .ecosystem import (
    LearnerHypothesis,
    LifecycleStage,
    MemoryBranch,
    MemoryCheckpoint,
    MemoryEcosystemEngine,
    MemoryLifecycle,
    MemoryPassport,
    MemoryRelationship,
    SynapticChangeLedger,
    UnifiedTimelineEvent,
)
from .studio import (
    ABComparisonResult,
    ComputationStep,
    ExperimentHypothesis,
    ExperimentNote,
    ExperimentResult,
    ExperimentStudioEngine,
    ParameterSweepPoint,
    ParameterSweepResult,
    StudioExperimentConfig,
    SynapticDeltaRecord,
)
from .research import (
    ClaimTrace,
    MetricDefinition,
    PrimaryResearchPaper,
    ResearchGraphEdge,
    ResearchGraphNode,
    ScientificResearchEngine,
    SourceLicenseRecord,
    PRIMARY_PAPERS,
    CLAIM_TRACES,
    METRIC_GLOSSARY,
    SOURCE_LICENSES,
)
from .synaptic import (
    SynapticBrain,
    SynapticConnection,
    SynapticExplanation,
    SynapticNetworkState,
    SynapticNeuron,
    SynapticPathway,
    SynapticRecallResult,
    extract_synaptic_state_from_experiment,
)
from .task import Query, Task, TaskConfig, generate_task

__version__ = "0.4.0"

__all__ = [
    "Event",
    "Experiment",
    "ExperimentConfig",
    "MECHANISM_INFO",
    "MECHANISM_REGISTRY",
    "METRIC_DEFINITIONS",
    "MechanismParams",
    "Memory",
    "Query",
    "RecallResult",
    "SCENARIOS",
    "SIMILARITY_MEASURES",
    "Task",
    "TaskConfig",
    "TextMemory",
    "UpdateResult",
    "ablate_event",
    "analyze_memory_contribution",
    "capacity_sweep",
    "collision_report",
    "compare_experiments",
    "compare_states",
    "compute_metrics",
    "create_mechanism",
    "encode_memory",
    "experiment_timeline",
    "generate_task",
    "inspect_state",
    "interference_matrix",
    "interference_model",
    "load_experiment",
    "order_comparison",
    "recall_memory",
    "retention_curve",
    "run_experiment",
    "run_scenario",
    "save_experiment",
    "similarity",
    "strength_sweep",
    "write_memory",
    "write_memories",
    "LabExperiment",
    "Hypothesis",
    "HypothesisStatus",
    "Prediction",
    "PredictedDirection",
    "CompetingHypothesesGroup",
    "Variable",
    "VARIABLE_REGISTRY",
    "ExperimentValidator",
    "ExperimentGraph",
    "ExperimentQueue",
    "run_condition_trials",
    "run_parameter_sweep",
    "run_grid_sweep",
    "run_controlled_comparison",
    "reproduce_lab_experiment",
    "analyze_sweep_relationship",
    "detect_nonlinear_patterns",
    "suggest_next_experiment",
    "find_discriminating_experiment",
    "diff_lab_experiments",
    "generate_scientific_report",
    "export_experiment_json",
    "export_experiment_csv",
    # Phase 04 Counterfactual
    "InterventionType",
    "DivergenceClassification",
    "ReplayStrategy",
    "CounterfactualStatus",
    "BranchType",
    "Intervention",
    "CounterfactualValidationError",
    "validate_intervention",
    "Timeline",
    "TimelineNode",
    "CounterfactualTree",
    "DivergenceStep",
    "DivergenceProfile",
    "compute_divergence_profile",
    "classify_divergence",
    "CounterfactualExperiment",
    "prepare_counterfactual_task",
    "replay_counterfactual_engine",
    "run_counterfactual",
    "create_ablation",
    "create_surgery",
    "reproduce_counterfactual",
    "compare_multiple_histories",
    "diff_histories",
    "generate_counterfactual_explanation",
    "estimate_event_contribution",
    "search_counterfactuals",
    "find_minimal_intervention",
    "export_counterfactual_json",
    "export_divergence_csv",
    # Synaptic Brain
    "SynapticBrain",
    "SynapticNeuron",
    "SynapticConnection",
    "SynapticPathway",
    "SynapticExplanation",
    "SynapticRecallResult",
    "SynapticNetworkState",
    "extract_synaptic_state_from_experiment",
    "extract_synaptic_history_from_experiment",
    # Phase 17 Collision Lab
    "CollisionMemory",
    "CollisionConfig",
    "SynapticPathwayClassification",
    "CollisionResult",
    "run_collision_experiment",
    "run_three_condition_suite",
    "run_order_comparison",
    "perform_collision_surgery",
    "perform_collision_counterfactual",
    # Phase 18 Memory Detective & Research Lab
    "InvestigationCase",
    "EvidenceItem",
    "CandidateHypothesis",
    "DetectiveScore",
    "CaseGenerator",
    "score_investigation",
    "CustomExperimentConfig",
    "CustomExperimentResult",
    "ResearchLabEngine",
    "ScientificSource",
    "VERIFIED_SOURCES",
    "CORE_LEARNING_OBJECTIVES",
    # Phase 19 Adaptive Memory Observatory
    "AdaptiveObservatoryEngine",
    "ObservatorySession",
    "ObservatorySnapshot",
    "ObservatoryProbe",
    "StreamEvent",
    "SynapticWeatherPoint",
    "ChangeDetection",
    "StabilityPlasticityMetrics",
    "EnvironmentShiftReport",
    "LearnerPrediction",
    # Phase 20 Memory Genome & Synaptic Fingerprint
    "SynapticFingerprint",
    "FingerprintComparison",
    "FingerprintEvolution",
    "MemoryDistancePoint",
    "MemoryDistanceMap",
    "MemoryBranchNode",
    "OutlierReport",
    "FingerprintChallenge",
    "MemoryGenomeEngine",
    # Phase 21 Memory Ecosystem
    "MemoryPassport",
    "LifecycleStage",
    "MemoryLifecycle",
    "UnifiedTimelineEvent",
    "MemoryBranch",
    "MemoryCheckpoint",
    "SynapticChangeLedger",
    "MemoryRelationship",
    "LearnerHypothesis",
    "MemoryEcosystemEngine",
    # Phase 22 Experiment Studio
    "StudioExperimentConfig",
    "ExperimentHypothesis",
    "ComputationStep",
    "SynapticDeltaRecord",
    "ExperimentResult",
    "ABComparisonResult",
    "ParameterSweepPoint",
    "ParameterSweepResult",
    "ExperimentNote",
    "ExperimentStudioEngine",
    # Phase 23 Scientific Evidence & Research Layer
    "PrimaryResearchPaper",
    "ClaimTrace",
    "MetricDefinition",
    "ResearchGraphNode",
    "ResearchGraphEdge",
    "SourceLicenseRecord",
    "ScientificResearchEngine",
    "PRIMARY_PAPERS",
    "CLAIM_TRACES",
    "METRIC_GLOSSARY",
    "SOURCE_LICENSES",
    "__version__",
    "SCHEMA_VERSION",
]